<?php
    session_start();
    unset($_SESSION['user_id']);
    unset($_SESSION['email']);
    unset($_SESSION['username']);
    unset($_SESSION['password']);
    unset($_SESSION['admin_login']);
    header('location:login.php');
    die();
?>